### ISSUE TITLE
Update active-monitor deployment to be compatible to kubernetes 1.22

### ISSUE THREAD

**Issue by RaviHari** [keikoproj/active-monitor#105]
**Is your feature request related to a problem? Please describe.**
Kubernetes 1.22 has some breaking changes so need to update the resources for deployment to be compatible such that users can use active-monitor in latest versions of kubernetes.

**Comment by tekenstam** [comment]
@RaviHari Part of this may be to [migrate from kubebuilder v2 to v3](https://book.kubebuilder.io/migration/v2vsv3.html).
