### ISSUE TITLE
Extend support for custom metrics

### ISSUE THREAD

**Issue by davemasselink** [keikoproj/active-monitor#11]
**Is your feature request related to a problem? Please describe.**
After this project was converted to kubebuilder style, custom metrics haven't been tested and confirmed to work.

**Describe the solution you'd like**
The aim of this ticket is to confirm this and update README accordingly

**Comment by samkeet** [comment]
I would like to give this a try.

**Comment by davemasselink** [comment]
hey @samkeet, thanks for your interest in the project! I've assigned the ticket to you.

up for meeting over tea/coffee early next week to discuss?

**Comment by samkeet** [comment]
@davemasselink Sure let's meet up next week. I would like to understand the requirements and the scope of the issue.

**Comment by davemasselink** [comment]
@samkeet, great to talk with you about this work today.

we'll also want to ensure that documentation is complete and correct... so if you come across any aspects of the README which are incomplete or confusing, please feel free to update and improve that file as a part of your work too

I'm not finding a good example of using custom metrics with the earlier version of the project... so we may also want to create a new example workflow which will act as a template for supporting custom metrics
