### ISSUE TITLE
Extend support for cluster/namespace scoping of healthcheck

### ISSUE THREAD

**Issue by davemasselink** [keikoproj/active-monitor#12]
**Is your feature request related to a problem? Please describe.**
This project had previously supported healthchecks being defined either as cluster or namespace scoping.

**Describe the solution you'd like**
This feature needs to be confirmed to still work. It may also require some design work to ensure it's still a necessary feature.

**Comment by RaviHari** [comment]
I would like to pick this up. Please let me know if this is okay.

**Comment by davemasselink** [comment]
@RaviHari, absolutely! the description above is fairly terse... so be sure to post here or reach out to me directly if any questions or opportunities for clarification come up.

Thanks!

**Comment by davemasselink** [comment]
hey @RaviHari, I had the chance to sync with @shrinandj this afternoon on the topic

the most important aspects coming out of the discussion are:
* this feature had NOT been supported in the previous instantiation of the project, therefore it will be wholly new
* "scope" may not be the best term to describe the feature, it's already overloaded in the k8s/crd world in this way: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition
* it IS a feature which @shrinandj sees value in building

by default, healthchecks are effectively "cluster" scoped. the work will be to support an example which he and I ran thru on the whiteboard

![Image from iOS (5)](https://user-images.githubusercontent.com/565727/66438998-22128d80-e9e3-11e9-812a-ffed65c54d3c.jpg)

(I'll add more details about the use-case indicated in the picture shortly)

**Comment by RaviHari** [comment]
Thanks @davemasselink and @shrinandj for the details
