### ISSUE TITLE
Support for k8s versions 1.24+

### ISSUE THREAD

**Issue by rkilingr** [keikoproj/active-monitor#145]
**Describe the bug**
Need to support updated version of [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) to be compatible with latest k8s versions.

**To Reproduce**
1. Run on a cluster with k8s version 1.24+
2. Observe that healthchecks fail to schedule because of unmountable service account secrets

**Expected behavior**
Need to work k8s versions 1.24+ as well.

**Screenshots**
![image](https://github.com/keikoproj/active-monitor/assets/17066394/0857ec82-a204-4e63-9983-d81c24e32b4e)

**Version**

```shell
v0.11.2
```

**Logs**

```shell
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    64s               default-scheduler  Successfully assigned addon-active-monitor-ns/aws-instance-limits-healthcheck-workflow-4vn4f to ***
  Warning  FailedMount  0s (x8 over 64s)  kubelet            MountVolume.SetUp failed for volume "exec-sa-token" : secret "active-monitor-instance-limits-sa.service-account-token" not found
```

**Have you thought about contributing a fix yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](../CONTRIBUTING.md), then reach out to us on [Slack](https://keikoproj.slack.com/app_redirect?channel=active-monitor) so we can see how to get you started.

**Comment by tekenstam** [comment]
Fixed by #146
