### ISSUE TITLE
kubectl describe healthcheck does not get expected health status

### ISSUE THREAD

**Issue by pzou1974** [keikoproj/active-monitor#2]
kubectl describe healthcheck does not get expected health status 

**Step to reproduce ** 
# step 1: install argo workflow-controller

kubectl apply -f https://raw.githubusercontent.com/orkaproj/active-monitor/master/deploy/deploy-argo.yaml

# step 2: install active-monitor controller

kubectl apply -f https://raw.githubusercontent.com/orkaproj/active-monitor/master/config/crd/bases/activemonitor.orkaproj.io_healthchecks.yaml
kubectl apply -f https://raw.githubusercontent.com/orkaproj/active-monitor/master/deploy/deploy-active-monitor.yaml
#step 3 
make run
#step 4 
kubectl create -f examples/inlineHello.yaml
#step 5
 kubectl get healthcheck -n health
----
NAME                 AGE
inline-hello-fbgj9   5m
----
#step 6
kubectl describe healthcheck inline-hello-fbgj9  -n health
get result without readme suggested
...
Status:
  Failed Count:              0
  Finished At:               timestampe
  Last Successful Workflow:  inline-hello-fbgj9 
  Status:                    Succeeded
  Success Count:             
Events:                      <none>

**Comment by davemasselink** [comment]
I am investigating this condition. It appears that the most likely cause is that the Argo workflow controller isn't up and running to process the workflow resources spurred by healthcheck creation. Likely, the outcome of this ticket will be to improve installation guide documentation such that necessary Argo related pieces are known to be installed prior to attempting to create a new healthcheck resource.

**Comment by davemasselink** [comment]
@pzou1974, I can't replicate your observations.

I've tried so far in a fresh KIND cluster as well as a fresh minikube cluster. You were working with an IKS cluster, is that correct?

The closest I've come to replicating what you saw occurs when I use a KIND cluster with minimal mem/cpu resources allocated. In that case, the newly submitted healthcheck simply continues in the "Running" phase for >2 minutes while the corresponding argo workflow is pulling and creating containers. During this stretch of time, the status block from the `kubectl describe ...` command is empty. As soon as a workflow succeeds or fails, however, the status block is present.

I'm going to try with a fresh IKS and AWS cluster using Shri's quick cluster creation script and if I can't get that setup to behave as you observed, I'll either sync with your or close this ticket.

**Comment by davemasselink** [comment]
whoops, should have closed this earlier. I feel confident in `active-monitor-controller`'s ability to marshal a health check thru its wf lifecycle and capture necessary events such that the healthcheck status can be built
