### ISSUE TITLE
Reduce code complexity

### ISSUE THREAD

**Issue by pzou1974** [keikoproj/active-monitor#4]
metrics\collector.go

<img width="833" alt="Screen Shot 2019-08-12 at 1 47 45 PM" src="https://user-images.githubusercontent.com/10687229/62897374-f6876580-bd07-11e9-951d-10feb383608c.png">

We can remove to if layer to 
```
if workflowStatus.Outputs == nil {
  return
}
if workflowStatus.Outputs.Parameters == nil {
  return
}
for ...
   for
```

**Comment by pzou1974** [comment]
You may install
go get -u github.com/fzipp/gocyclo
and then run
gocyclo -over [n] .

**Comment by davemasselink** [comment]
thanks @pzou1974, it's a good reminder to remember to periodically check cyclic complexity and to look for opportunities to limit it when possible... especially when you provide some pseudocode suggestions of potential improvements :)

**Comment by thbishop-intuit** [comment]
I'd like to pick this one up

**Comment by davemasselink** [comment]
great, thanks @thbishop-intuit.

If you'd be interested, it would be great to setup a quick video/phone call with you where I could share some project history and context which may be valuable and then we could talk about the task a bit more.

I'll send you a mtg invite, feel free to counter on date/time or reject if you don't think it would be valuable.

**Comment by davemasselink** [comment]
work completed in #24
