### ISSUE TITLE
BUG: Workflow not recreated on next run

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/active-monitor#48]
**Describe the bug**
Workflow can be failed for some reason like scheduling and did not run but state is not changed in HealthCheck to reflect this error

**To Reproduce**
If we cannot reproduce, we cannot fix! Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste any relevant version print outputs here.
```

**Logs**

```shell
Paste any relevant application logs here.
```

**Have you thought about contributing a fix yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](../CONTRIBUTING.md), then reach out to us on [Slack](https://keikoproj.slack.com/app_redirect?channel=active-monitor) so we can see how to get you started.

**Comment by RaviHari** [comment]
Closing this as there are no details.
