### ISSUE TITLE
Add metrics to the status 

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/active-monitor#49]
**Is your feature request related to a problem? Please describe.**
Add:
- Total
- LastSuccess
- LastFailure

**Describe the solution you'd like**

**Have you thought about contributing yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](../CONTRIBUTING.md), then reach out to us on [Slack](https://keikoproj.slack.com/app_redirect?channel=active-monitor) so we can see how to get you started.

**Comment by RaviHari** [comment]
@kevdowney this is already available from this PR: https://github.com/keikoproj/active-monitor/pull/35

![image](https://user-images.githubusercontent.com/7333720/83320955-c47ccb00-a269-11ea-8930-f2f84161673a.png)

Are you looking for LastFailure workflow and Total as separate fields in status?

**Comment by vasukiprasad1** [comment]
The idea here is to capture the custom return message from the workflow controller and based on the message derive the status of the workflow(success/failure).  Along with the monitoring counter, it will be nice to have a binary type of reporting for workflow status. Setting the alert makes it easier and manageable.
