### ISSUE TITLE
Enable/Disable flag in HealthCheckSpec 

### ISSUE THREAD

**Issue by vasukiprasad1** [keikoproj/active-monitor#62]
**Is your feature request related to a problem? Please describe.**

Having an Enable/Disable flag in HealthCheckSpec will provide the flexibility to stop monitoring on individual a given cluster. Sometime we might encounter a problematic situation on a cluster with this flag in place we can instruct the controller not to process the health check on a given cluster until the problem is addressed. 
- Noise alerts can be addressed instantly 
- Cluster upgrade operation can be avoided for just to disable a HealthCheck

**Describe the solution you'd like**
Under the HealthCheckSpec struct, we should add a field called EnableHealthCheck set to true by default and if set to false. The controller reconciler shouldn't process the HealthCheck. This field should be read dynamically.

We will have to handle this under the process workflow method.

**Have you thought about contributing yourself?**
Yes I would like to work on this solution.
Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](../CONTRIBUTING.md), then reach out to us on [Slack](https://keikoproj.slack.com/app_redirect?channel=active-monitor) so we can see how to get you started.

**Comment by RaviHari** [comment]
Active-Monitor workflows can be paused by setting repeatAfterSec to <= 0 and by not specifying the schedule for cron.
Closing this as there is a way to achieve this.
