### ISSUE TITLE
Clean-up example/sample workflows

### ISSUE THREAD

**Issue by davemasselink** [keikoproj/active-monitor#8]
**Is your feature request related to a problem? Please describe.**
Currently, the project contains both an `examples/` as well as a `sample-workflows/` directory. The directory names and corresponding documentation references don't really make it clear why both directories exist and when a new workflow should be added to one or the other.

**Describe the solution you'd like**
Instead, it would likely be best to consolidate all example or sample workflows into a single directory and ensure that all documentation references are up-to-date. Further, the README should be extended to explain what a contributor wanting to add a new example workflow aught to do and where it should be added.

**Comment by Susritha** [comment]
I would like to take this up!

**Comment by Susritha** [comment]
@davemasselink , Can you assign me to this issue

**Comment by davemasselink** [comment]
Thanks, @tekenstam, for helping out with the assignment. I hadn't realized that the repo was configured such that all folks couldn't simply self assign.

@Susritha, fantastic... thanks for your interest in the project.

Up for a video chat to talk thru the goals of this issue early next week? Maybe Tuesday, 08Oct at 2pm?

**Comment by Susritha** [comment]
@davemasselink , yes I'm free the coming Tuesday for a chat.

**Comment by davemasselink** [comment]
@Susritha, great... sent you a mtg invite. Talk with you soon.

**Comment by davemasselink** [comment]
* folder under `/examples` named `/workflows`
* move the `deployment-workflow.yaml` file there
* extend README docs to indicate where a user should add a new healthcheck or workflow
